# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np 

x = np.arange(10)
print(x.reshape(2,5))


[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
x = np.arange(10).reshape(2,5)
a = np.ones((2,5), dtype= 'int16')
np.vstack((x,a))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
x = np.arange(10).reshape(2,5)
a = np.ones((2,5), dtype= 'int16')
np.hstack((x,a))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
b = np.arange(10).reshape(2,5)
np.concatenate(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr3d = np.arange(15).reshape(3,1,5)
print(arr3d)#(depth, rows,columns)

a=arr3d.reshape(arr3d.size)
a

[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
a.reshape(3,1,5)

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
a = np.arange(30).reshape(5,6)
np.mean(a)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
np.std(a)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(a)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
np.transpose(a)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [14]:
ab = np.array(([2,3,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17]))
print(ab)
np.trace(ab)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


38

## Question:13

### Find the determinant of the previous array in Q12?

In [35]:
np.linalg.det(ab)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [17]:
arr = np.array(([2,3,4,5],[6,7,8,9],[10,11,12,13],[14,15,16,17]))
print("5th percentile",np.percentile(arr,5))
print("95th percentile",np.percentile(arr,95))

5th percentile 2.75
95th percentile 16.25


## Question:15

### How to find if a given array has any null values?

In [32]:
arr = np.array(([2,3,np.NaN,5],[6,7,8,9],[10,np.NaN,12,13],[np.NaN,15,16,0]))
np.isnan(arr) # where true gives us null values.

array([[False, False,  True, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True, False, False, False]])